default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tiq_development

test:
  <<: *default
  database: tiq_test

production:
  <<: *default
  database: tiq_production
  username: tiq
  password: <%= ENV['TIQ_DATABASE_PASSWORD'] %>
